In [1]:
l = [2312,2434,34534,2435]

In [2]:
l

[2312, 2434, 34534, 2435]

In [3]:
import numpy as np

In [5]:
a = np.array(l)

In [6]:
a

array([ 2312,  2434, 34534,  2435])

In [11]:
b = np.array([12,455,634,64.5,True,'abc'])

In [12]:
b

array(['12', '455', '634', '64.5', 'True', 'abc'], dtype='<U32')

In [13]:
print(b)

['12' '455' '634' '64.5' 'True' 'abc']


In [14]:
l.pop()

2435

In [15]:
l

[2312, 2434, 34534]

In [16]:
a.mean()

10428.75

In [17]:
a.argmax()

2

In [18]:
a

array([ 2312,  2434, 34534,  2435])

In [19]:
a.argmin()

0

In [20]:
a.sort()

In [21]:
a

array([ 2312,  2434,  2435, 34534])

In [23]:
l[1:]

[2434, 34534]

In [24]:
l[::]

[2312, 2434, 34534]

In [25]:
l.append(34)

In [26]:
l

[2312, 2434, 34534, 34]

In [27]:
a = np.array(l)

In [28]:
a

array([ 2312,  2434, 34534,    34])

In [29]:
a[2:]

array([34534,    34])

In [30]:
a[2:4]

array([34534,    34])

In [31]:
a[1:3]

array([ 2434, 34534])

In [32]:
b = a[1:3]

In [33]:
b

array([ 2434, 34534])

In [34]:
b[0]

2434

In [35]:
b[:]

array([ 2434, 34534])

In [36]:
b[:]=111

In [37]:
b

array([111, 111])

In [38]:
a

array([2312,  111,  111,   34])

---

In [39]:
# when you are slicing an array(creating a new array 'b' from an old array 'a', you are not creating a new array, you are just getting the same array or more precisely, you are getting a "view" of the orignal array. anything that you do with the new array i.e. with the view of the original array, will actually modify the original array.)

In [40]:
# Python does this to save memory space. By not creating new arrays and just creating views of the old array, numpy (or Python) saves disk space. 

In [41]:
# to actually get a new array out of an old array and to modify the new array without hurting the old array. Use the .copy() method on the old array.

In [42]:
c = a.copy()

In [43]:
c

array([2312,  111,  111,   34])

In [44]:
a

array([2312,  111,  111,   34])

In [45]:
c[0]=-32

In [46]:
c

array([-32, 111, 111,  34])

In [47]:
a

array([2312,  111,  111,   34])

In [48]:
import scrapy